# track_user:
#   path: /user
#   defaults: {_controller: TestBundle:User:new }


# track_user:
#   path: /user
#   defaults: { _controller: TestBundle:User:user }

user:
  path: /new
  defaults: { _controller: TestBundle:User:user }

user:
  path: /success
  defaults: { _controller: TestBundle:User:success }
