new_user:
  path: /new
  defaults: { _controller: UserBundle:User:new}

list_user:
  path: /
  defaults: { _controller: UserBundle:User:list}

edit_user:
  path: /edit/{id}
  defaults: { _controller: UserBundle:User:edit}
  requirements:
    id: '[0-9]+'

view_user:
  path: /{id}
  defaults: { _controller: UserBundle:User:view}
  requirements:
    id: '[0-9]+'