new_user:
  path: /new
  defaults: { _controller: UserBundle:User:new}

admin:
  path: /admin
  defaults: { _controller: UserBundle:User:admin}

interest:
  path: /admin/interest
  defaults: { _controller: UserBundle:User:addInterest}

graduation:
  path: /admin/graduation
  defaults: { _controller: UserBundle:User:addGraduation}

list_user:
  path: /
  defaults: { _controller: UserBundle:User:list}
  
display_user:
  path: /display/{page}
  defaults: { _controller: UserBundle:User:display, page: 1}
  requirements:
    page: '\d+'

edit_user:
  path: /edit/{id}
  defaults: { _controller: UserBundle:User:edit}
  requirements:
    id: '\d+'

view_user:
  path: /{id}
  defaults: { _controller: UserBundle:User:view}
  requirements:
    id: '\d+'

login:
    path: /login
    defaults: { _controller:  UserBundle:User:login }
