new_user:
  path: /new
  defaults: { _controller: UserBundle:User:new}

list_user:
  path: /list/{page}
  defaults: { _controller: UserBundle:User:list, page: 1}
  requirements:
    page: '\d+'
    
edit_user:
  path: /edit/{id}
  defaults: { _controller: UserBundle:User:edit}
  requirements:
    id: '\d+'

view_user:
  path: /{id}
  defaults: { _controller: UserBundle:User:view}
  requirements:
    id: '\d+'