new_user:
  path: /new
  defaults: { _controller: UserBundle:User:new}

list_user:
  path: /
  defaults: { _controller: UserBundle:User:list}

edit_user:
  path: /edit
  defaults: { _controller: UserBundle:User:edit}